/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const JQueryFormBuilderLazyImport = createFileRoute('/jQueryFormBuilder')()
const FormioLazyImport = createFileRoute('/formio')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const JQueryFormBuilderLazyRoute = JQueryFormBuilderLazyImport.update({
  path: '/jQueryFormBuilder',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/jQueryFormBuilder.lazy').then((d) => d.Route),
)

const FormioLazyRoute = FormioLazyImport.update({
  path: '/formio',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/formio.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/formio': {
      id: '/formio'
      path: '/formio'
      fullPath: '/formio'
      preLoaderRoute: typeof FormioLazyImport
      parentRoute: typeof rootRoute
    }
    '/jQueryFormBuilder': {
      id: '/jQueryFormBuilder'
      path: '/jQueryFormBuilder'
      fullPath: '/jQueryFormBuilder'
      preLoaderRoute: typeof JQueryFormBuilderLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  FormioLazyRoute,
  JQueryFormBuilderLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/formio",
        "/jQueryFormBuilder"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/formio": {
      "filePath": "formio.lazy.tsx"
    },
    "/jQueryFormBuilder": {
      "filePath": "jQueryFormBuilder.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
