/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const JoyfillLazyImport = createFileRoute('/joyfill')()
const JQueryFormBuilderLazyImport = createFileRoute('/jQueryFormBuilder')()
const FormioRendererLazyImport = createFileRoute('/formioRenderer')()
const FormioBuilderLazyImport = createFileRoute('/formioBuilder')()
const FormEngineLazyImport = createFileRoute('/formEngine')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const JoyfillLazyRoute = JoyfillLazyImport.update({
  path: '/joyfill',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/joyfill.lazy').then((d) => d.Route))

const JQueryFormBuilderLazyRoute = JQueryFormBuilderLazyImport.update({
  path: '/jQueryFormBuilder',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/jQueryFormBuilder.lazy').then((d) => d.Route),
)

const FormioRendererLazyRoute = FormioRendererLazyImport.update({
  path: '/formioRenderer',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/formioRenderer.lazy').then((d) => d.Route),
)

const FormioBuilderLazyRoute = FormioBuilderLazyImport.update({
  path: '/formioBuilder',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/formioBuilder.lazy').then((d) => d.Route))

const FormEngineLazyRoute = FormEngineLazyImport.update({
  path: '/formEngine',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/formEngine.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/formEngine': {
      id: '/formEngine'
      path: '/formEngine'
      fullPath: '/formEngine'
      preLoaderRoute: typeof FormEngineLazyImport
      parentRoute: typeof rootRoute
    }
    '/formioBuilder': {
      id: '/formioBuilder'
      path: '/formioBuilder'
      fullPath: '/formioBuilder'
      preLoaderRoute: typeof FormioBuilderLazyImport
      parentRoute: typeof rootRoute
    }
    '/formioRenderer': {
      id: '/formioRenderer'
      path: '/formioRenderer'
      fullPath: '/formioRenderer'
      preLoaderRoute: typeof FormioRendererLazyImport
      parentRoute: typeof rootRoute
    }
    '/jQueryFormBuilder': {
      id: '/jQueryFormBuilder'
      path: '/jQueryFormBuilder'
      fullPath: '/jQueryFormBuilder'
      preLoaderRoute: typeof JQueryFormBuilderLazyImport
      parentRoute: typeof rootRoute
    }
    '/joyfill': {
      id: '/joyfill'
      path: '/joyfill'
      fullPath: '/joyfill'
      preLoaderRoute: typeof JoyfillLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  FormEngineLazyRoute,
  FormioBuilderLazyRoute,
  FormioRendererLazyRoute,
  JQueryFormBuilderLazyRoute,
  JoyfillLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/formEngine",
        "/formioBuilder",
        "/formioRenderer",
        "/jQueryFormBuilder",
        "/joyfill"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/formEngine": {
      "filePath": "formEngine.lazy.tsx"
    },
    "/formioBuilder": {
      "filePath": "formioBuilder.lazy.tsx"
    },
    "/formioRenderer": {
      "filePath": "formioRenderer.lazy.tsx"
    },
    "/jQueryFormBuilder": {
      "filePath": "jQueryFormBuilder.lazy.tsx"
    },
    "/joyfill": {
      "filePath": "joyfill.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
